# Generated by Django 2.2.3 on 2019-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('company', 'company'), ('client', 'client')], max_length=20),
        ),
    ]
