# Generated by Django 2.2.3 on 2019-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190805_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='education',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='experience',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='skill',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
